### ISSUE TITLE
Missing Dicoogle 3 methods

### ISSUE THREAD

**Issue by Enet4** [bioinformatics-ua/dicoogle-client-js#36]
- [x] `GET export/list`: get the DICOM field list for export (#38)
- [x] `GET presets`: get all export presets (#38)
- [x] `POST presets/{username}/{name}`: save export preset (#38)
- [x] `POST plugins/{type}/{name}/enable`: enable a plugin (#39)
- [x] `POST plugins/{type}/{name}/disable`: disable a plugin (#39)
- [x] ~~`GET login`: get the details of an existing user session~~ `restoreSession` already exists, clarify library on this #40
